name: Hue Lights

on:
  workflow_dispatch:

jobs:
  hue_lights:
    name: Hue Lights

    runs-on:
      - self-hosted
      - ARM

    environment:
      name: local

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute Hue Action
        id: hue
        uses: ./hue-lights-action
        with:
          bridge: ${{ secrets.HUE_BRIDGE_IP_ADDRESS }}
          username: ${{ secrets.HUE_USERNAME }}
          light_names:
            - Office Desk Left
            - Office corner

      - name: Display Lights
        run: echo "${{ steps.hue.outputs.lights }}"
