name: Run

on:
  workflow_dispatch:

jobs:
  run:
    name: Run

    runs-on: self-hosted

    steps:
      - name: Execute Python
        run: |
          python3 run.py
        working-directory: ./text
