name: Run

on:
  workflow_dispatch:

jobs:
  run:
    name: Run

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Execute Python Application
        run: |
          sudo python3 run.py images/thumbnail.jpg
        working-directory: ./images
